# Generated by Django 3.2.6 on 2021-08-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
    ]
