# Generated by Django 3.2.3 on 2021-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.CharField(default=12, max_length=3, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=12, max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
